#!/bin/csh

make all > /dev/null

# echo ""
# echo ">>Test dp"
# echo ""
# foreach i (`seq 1 8`)
#     cat tests/test$i
#     time ./target/liftdp < tests/test$i
#     echo ""
# end

echo ""
echo ">>Test mem"
echo ""
foreach i (`seq 1 8`)
    cat tests/test$i
    time ./target/liftmem < tests/test$i
    echo ""
end

# echo ""
# echo ">>Test bf"
# echo ""
# foreach i (`seq 1 8`)
#     cat tests/test$i
#     time ./target/liftbf < tests/test$i
#     echo ""
# end

# echo ""
# echo ">>Test rec"
# echo ""
# foreach i (`seq 1 8`)
#     cat tests/test$i
#     time ./target/liftrec < tests/test$i
#     echo ""
# end

make clean > /dev/null