figproc: figproc.c
	gcc -Wall -Wextra -Werror -o figproc figproc.c

convert: figproc.c
	gcc -Wall -Wextra -Werror -DOPTION=1 -o convert figproc.c

asciiboi: asciiboi.c
	gcc -Wall -Wextra -Werror -o asciiboi asciiboi.c
